environment:
  nodejs_version: "8"

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install --loglevel error --depth 0
  - set PATH=%APPDATA%\npm;%PATH%

test_script:
  - bin\build.cmd
  - dir dist /s
  - bin\tests.cmd
  - bin\cuke-api.cmd
  # - bin\cuke-cli.cmd
  - dir dist /s
  - dir C:\projects\text-runner\dist\cli
  - node dist\cli\cli.js
  # - bin\text-run.cmd


# Don't double-build PRs
skip_branch_with_pr: true

build: off
