environment:
  nodejs_version: "8"

# cache:
  # - node_modules

init:
  - git config --global core.autocrlf true
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install --loglevel error --depth 0
  - set PATH=%APPDATA%\npm;%PATH%

test_script:
  - make tests
  - make cuke-api
  - make cuke-cli
  - make docs


# Don't double-build PRs
skip_branch_with_pr: true

build: off
