environment:
  nodejs_version: "7"

cache:
  - node_modules

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install --loglevel error --depth 0
  - set PATH=%APPDATA%\npm;%PATH%

test_script:
  - bin\build.cmd
  - dir dist
  - node_modules\.bin\mocha --compilers ls:livescript spec\*.ls
  - bin\cuc-api
  - bin\cuc-cli
  - bin\text-run --format robust


# Don't double-build PRs
skip_branch_with_pr: true

build: off
