environment:
  nodejs_version: "8"

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install --loglevel error --depth 0
  - set PATH=%APPDATA%\npm;%PATH%

test_script:
  - dir
  - cd
  - "bin\\build.cmd"
  - "bin\\tests.cmd"
  - node_modules\.bin\cucumber-js --tags '(not @clionly) and (not @todo) and (not @skipWindows)' --format progress
  - "bin\\cuke-cli.cmd"
  - "bin\\text-run.cmd"


# Don't double-build PRs
skip_branch_with_pr: true

build: off
