environment:
  nodejs_version: "7"

cache:
  - node_modules

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install --loglevel error --depth 0
  - set PATH=%APPDATA%\npm;%PATH%

test_script:
  - node_modules\o-tools-livescript\bin\build.cmd
  - bin\tests
  - bin\cuke-api
  - bin\cuke-cli
  - bin\text-run --format robust


# Don't double-build PRs
skip_branch_with_pr: true

build: off
