version: 2

defaults: &defaults

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: restore Yarn cache
          keys:
            - yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-{{ .Branch }}
            - yarn-master
            - yarn-
      - run: yarn
      - run: make build-all
      - run: make test-all
      - save_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo
      - save_cache:
          name: save Yarn cache
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
