version: 2

defaults: &defaults

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            make build-all
          else
            make build-involved
          fi
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            make test-all
          else
            make test-affected
          fi
