version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: restore Yarn cache
          keys:
            - yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-{{ .Branch }}
            - yarn-master
            - yarn-
      - run: yarn
      - run: make build-involved
      - save_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo
      - save_cache:
          name: save Yarn cache
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  text-runner-cuke:
    <<: *defaults
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd text-runner && ../.circleci/run-if-affected make cuke-ci

  text-runner-others:
    <<: *defaults
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd text-runner && ../.circleci/run-if-affected make lint unit docs

  textrun-action:
    <<: *defaults
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd textrun-action && ../.circleci/run-if-affected make test-ci

  textrun-javascript:
    <<: *defaults
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd textrun-javascript && ../.circleci/run-if-affected make test

  textrun-npm:
    <<: *defaults
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd textrun-npm && ../.circleci/run-if-affected make test

  textrun-shell:
    <<: *defaults
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd textrun-shell && ../.circleci/run-if-affected make test

  send-coverage:
    <<: *defaults
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: coverage-tests-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: coverage-cuke-other-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: coverage-cuke-actions-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: coverage-cuke-tagtypes-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: coverage-docs-{{ .Environment.CIRCLE_SHA1 }}
      - run: ls -la
      - run: make coverage-merge
      - run: make coverage-send

  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_SHA1 }}
      - run: make build
      - run: npm set //registry.npmjs.org/:_authToken $AUTH_TOKEN
      - run: npm publish

workflows:
  version: 2

  testing:
    jobs:
      - checkout_code
      - text-runner-cuke:
          requires:
            - checkout_code
      - text-runner-others:
          requires:
            - checkout_code
      - textrun-action:
          requires:
            - checkout_code
      - textrun-javascript:
          requires:
            - checkout_code
      - textrun-npm:
          requires:
            - checkout_code
      - textrun-shell:
          requires:
            - checkout_code
#   - send-coverage:
#       requires:
#         - lint
#         - unit-tests
#         - cuke-other
#         - cuke-actions
#         - cuke-tagtypes
#         - doc-tests
