version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo building all codebases ...
            make build-all
          else
            echo building involved codebases ...
            make build-involved
          fi
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo testing all codebases ...
            make test-all-ci
          else
            echo testing affected codebases
            make test-affected-ci
          fi
