version: 2

defaults: &defaults

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - run: make build-all
      - run: make test-all
