name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - run: env
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # - run: |
      #     if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #       echo building all codebases ...
      #       make build-all
      #     else
      #       echo building involved codebases ...
      #       make build-involved
      #     fi
      # - run: make setup
      # - run: npm run build --if-present
      # - run: npm test
